language: python
python:
  - "3.6.5"
install:
  - pip install -r requirements.txt
  - pip install coverage pytest pytest-cov codecov
script:
  - pytest --cov=./
after_success:
  - codecov -t c1f43188-dfd5-4d7f-9031-b1c3fe58e6ce
